services:

  proxy:
    ports:
      - "80:80"      
    command:
      # Enable Docker in Traefik, so that it reads labels from Docker services
      - --providers.docker
      # Add a constraint to only use services with the label for this stack
      # from the env var TRAEFIK_TAG
      - --providers.docker.constraints=Label(`traefik.constraint-label-stack`, `localhost`)
      # Do not expose all Docker services, only the ones explicitly exposed
      - --providers.docker.exposedbydefault=false
      # Disable Docker Swarm mode for local development
      # - --providers.docker.swarmmode
      # Enable the access log, with HTTP requests
      - --accesslog
      # Enable the Traefik log, for configurations and errors
      - --log
      # Enable the Dashboard and API
      - --api
      # Enable the Dashboard and API in insecure mode for local development
      - --api.insecure=true
    labels:
      - traefik.enable=true
      - traefik.http.routers.goyangi-traefik-public-http.rule=Host(`localhost`)
      - traefik.http.services.goyangi-traefik-public.loadbalancer.server.port=80

  db:
    ports:
      - "5432:5432"

  pgadmin:
    ports:
      - "5050:5050"

  backend:    
    environment:      
      - SERVER_HOST=http://localhost
    depends_on:
      - db      
    build:      
      dockerfile: backend.dockerfile
      target: prod
      args:
        INSTALL_DEV: ${INSTALL_DEV-true}                
    labels:
      - traefik.enable=true
      - traefik.constraint-label-stack=localhost
      - traefik.http.routers.goyangi-backend-http.rule=PathPrefix(`/api`) || PathPrefix(`/swagger`)      
      - traefik.http.services.goyangi-backend.loadbalancer.server.port=80

  frontend:
    build:
      context: ./frontend/vuejs
      args:
        FRONTEND_ENV: dev
    labels:
      - traefik.enable=true
      - traefik.constraint-label-stack=localhost
      - traefik.http.routers.goyangi-frontend-http.rule=PathPrefix(`/`)
      - traefik.http.services.goyangi-frontend.loadbalancer.server.port=80

networks:
  traefik-public:
    # For local dev, don't expect an external Traefik network
    external: false
