# Gopkg.toml example
#
# Refer to https://golang.github.io/dep/docs/Gopkg.toml.html
# for detailed Gopkg.toml documentation.
#
# required = ["github.com/user/thing/cmd/thing"]
# ignored = ["github.com/user/project/pkgX", "bitbucket.org/user/project/pkgA/pkgY"]
#
# [[constraint]]
#   name = "github.com/user/project"
#   version = "1.0.0"
#
# [[constraint]]
#   name = "github.com/user/project2"
#   branch = "dev"
#   source = "github.com/myfork/project2"
#
# [[override]]
#   name = "github.com/x/y"
#   version = "2.4.0"
#
# [prune]
#   non-go = false
#   go-tests = true
#   unused-packages = true


[[constraint]]
  name = "github.com/Sirupsen/logrus"
  version = "1.4.2"

[[constraint]]
  name = "github.com/codegangsta/cli"
  version = "1.20.0"

[[constraint]]
  branch = "master"
  name = "github.com/daddye/vips"

[[constraint]]
  name = "github.com/disintegration/gift"
  version = "1.2.0"

[[constraint]]
  name = "github.com/garyburd/redigo"
  version = "1.6.0"

[[constraint]]
  name = "github.com/gin-contrib/cors"
  version = "1.3.0"

[[constraint]]
  name = "github.com/gin-gonic/gin"
  version = "1.4.0"

[[constraint]]
  branch = "master"
  name = "github.com/goamz/goamz"

[[constraint]]
  name = "github.com/gorilla/securecookie"
  version = "1.1.1"

[[constraint]]
  name = "github.com/jinzhu/gorm"
  version = "1.9.8"

[[constraint]]
  name = "github.com/lib/pq"
  version = "1.1.1"

[[constraint]]
  name = "github.com/mattes/migrate"
  version = "1.3.2"

[[constraint]]
  name = "github.com/nicksnyder/go-i18n"
  version = "1.10.0"

[[constraint]]
  name = "github.com/onsi/ginkgo"
  version = "1.8.0"

[[constraint]]
  name = "github.com/onsi/gomega"
  version = "1.5.0"

[[constraint]]
  branch = "master"
  name = "golang.org/x/crypto"

[[constraint]]
  branch = "master"
  name = "golang.org/x/net"

[[constraint]]
  branch = "master"
  name = "golang.org/x/oauth2"

[[constraint]]
  branch = "v1"
  name = "gopkg.in/gomail.v1"

[[constraint]]
  name = "gopkg.in/natefinch/lumberjack.v2"
  version = "2.1.0"

[[override]]
  source = "https://github.com/fsnotify/fsnotify/archive/v1.4.7.tar.gz"
  name = "gopkg.in/fsnotify.v1"

[prune]
  go-tests = true
  unused-packages = true
