export const authenticationTypes = {
  SET_API: 'SET_API',
  LOGIN: 'LOGIN',
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGOUT: 'LOGOUT'
}

export const userTypes = {
  SET_API: 'SET_API',
  CREATE_USER: 'CREATE_USER',
  CREATE_USER_SUCCESS: 'CREATE_USER_SUCCESS'
}

export const articleTypes = {
  SET_API: 'SET_API',
  PENDING: 'PENDING',
  DONE: 'DONE',
  SET_ARTICLE_LIST: 'SET_ARTICLE_LIST',
  NEW_ARTICLE: 'NEW_ARTICLE',
  SET_ARTICLE: 'SET_ARTICLE',
  SET_ARTICLE_COMMENT_LIST: 'SET_ARTICLE_COMMENT_LIST',
  SET_ARTICLE_LIKING_LIST: 'SET_ARTICLE_LIKING_LIST'
}

export const languageTypes = {
  CHANGE_LOCALE: 'CHANGE_LOCALE'
}
